name: Daily Release

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Create release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          tag_name: daily-${{ github.run_id }}
          name: Daily Release ${{ github.run_id }}
          body: Automated daily release.
